[package]
name = "proj-models"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derivative = "2.2.0"
serde = "1.0.200"
serde_derive = "1.0.200"
